### PR TITLE
[WIP] Cortical layers

### PR DESCRIPTION
**Pull request by lamblin**
This is @adri-romsor's loader for a 1D dataset for segmentation of cortical layers.
I'm wondering if it would make sense to include it here, and what would be needed for inclusion.

### CODE REVIEW

**Comment by lamblin** [comment]
Actually, most of the changes to `__init__.py` should probably go in a separate PR.

**Comment by fvisin** [comment]
Thanks for the PR. I begun looking into it (sorry in advance, I don't have much time in the next weeks but I'll try my best to do it in a reasonable amount of time) and it looks like there is *a lot* of duplicated code.

What are the main differences introduced by parallel_loader_1D? Do you think it would be possible to modify parallel_loader.py directly, e.g., by checking `self.data_shape` to detect the 1D case? If not, is there a way to reuse the code from parallel_loader.py, e.g., by splitting the existing methods in more fine-grained submethods that can be overridden by the 1D class?

> Actually, most of the changes to \_\_init\_\_.py should probably go in a separate PR.

It should indeed, but we can be not too formal on that, for this once. ;)
Thanks for those changes BTW, a nice improvement over what I wrote!

**Comment by lamblin** [comment]
Replaced by #5.

**Comment by lamblin** [comment]
And the changes in `__init__.py` are in #6.

**Pull request closed without merging**
